"""Generate java_vectors.json: reference values for the GC Bridge Android port.

The Android app (android/gcbridge) re-implements the Switch 2 report parsing, calibration
and BLE command building in Java. Its JVM unit tests read this file so the two
implementations can't drift apart. Regenerate after changing switch2_usb.py or
switch2_ble.py:

    python tests/fixtures/switch2/make_java_vectors.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT))

from controllerlog.input import switch2_ble as ble  # noqa: E402
from controllerlog.input import switch2_usb as usb  # noqa: E402


def u12_pair(a: int, b: int) -> bytes:
    return ble.pack_u12_pair(a, b)


def usb_report(model: str, buttons: dict[int, int], lx: int, ly: int, rx: int, ry: int,
               lt: int = 0, rt: int = 0) -> bytes:
    r = bytearray(64)
    r[0] = usb.REPORT_ID
    for byte, mask in buttons.items():
        r[byte] |= mask
    r[11:14] = u12_pair(lx, ly)
    r[14:17] = u12_pair(rx, ry)
    r[61], r[62] = lt, rt
    return bytes(r)


def cal_json(cal: usb.Calibration) -> dict:
    def axis(a: usb.AxisCal) -> dict:
        return {"neutral": a.neutral, "below": a.below, "above": a.above}
    return {"left": {"x": axis(cal.left.x), "y": axis(cal.left.y)},
            "right": {"x": axis(cal.right.x), "y": axis(cal.right.y)},
            "trigger_zero": list(cal.trigger_zero), "serial": cal.serial, "source": cal.source}


def main() -> None:
    out: dict = {"note": "generated by make_java_vectors.py; do not edit"}

    # --- USB input reports (report id 0x05, 64 bytes) -> canonical state ----------------
    reports = []
    gc_default = usb.Calibration.defaults("gamecube")
    pro_default = usb.Calibration.defaults("pro")
    factory_block = bytes(0x28) + u12_pair(2100, 1990) + u12_pair(1300, 1250) + u12_pair(1210, 1180)
    fake_flash = {
        0x13000: bytes([0, 0]) + b"HAC-TEST-0001\0\0\0" + bytes(0x40 - 18),
        0x13080: factory_block + bytes(0x40 - len(factory_block)),
        0x130C0: bytes(0x28) + u12_pair(2048, 2048) + u12_pair(1100, 1120) + u12_pair(1140, 1090)
                 + bytes(0x40 - 0x31),
        0x13140: bytes([28, 33]) + bytes(0x3E),
    }
    gc_factory = usb.read_calibration(lambda a: fake_flash.get(a), "gamecube")
    cases = [
        ("gamecube", gc_default, {}, 2048, 2048, 2048, 2048, 30, 30),
        ("gamecube", gc_default, {5: 0x04}, 2048, 2048, 2048, 2048, 30, 30),          # A
        ("gamecube", gc_default, {5: 0x01 | 0x02 | 0x08 | 0x80 | 0x40}, 2048, 2048, 2048, 2048, 0, 232),
        ("gamecube", gc_default, {6: 0x02 | 0x10 | 0x20 | 0x40, 7: 0x01 | 0x02 | 0x04 | 0x08 | 0x40 | 0x80},
         2048, 2048, 2048, 2048, 30, 30),
        ("gamecube", gc_default, {}, 4000, 100, 200, 3900, 131, 232),
        ("gamecube", gc_default, {}, 2070, 2030, 2048, 2048, 34, 30),                # inside deadzone
        ("gamecube", gc_factory, {5: 0x04}, 3400, 800, 1000, 3100, 28, 120),
        ("gamecube", gc_factory, {}, 700, 3300, 2048, 2048, 232, 33),
        ("pro", pro_default, {5: 0x01 | 0x02 | 0x04 | 0x08 | 0x40 | 0x80, 7: 0x80}, 2048, 2048, 2048, 2048),
        ("pro", pro_default, {6: 0x01 | 0x02 | 0x04 | 0x08 | 0x10 | 0x20 | 0x40, 8: 0x01 | 0x02},
         2048, 2048, 2048, 2048),
        ("pro", pro_default, {7: 0x01 | 0x02 | 0x04 | 0x08 | 0x40}, 500, 3600, 3600, 500),
        ("pro", pro_default, {}, 2048, 2048, 2048, 2048),
    ]
    for model, cal, buttons, lx, ly, rx, ry, *trig in cases:
        data = usb_report(model, buttons, lx, ly, rx, ry, *trig)
        st = usb.parse_report(model, data, cal)
        assert st is not None
        reports.append({"model": model, "calibration": cal_json(cal), "report": data.hex(),
                        "buttons": st.buttons, "axes": st.axes})
    out["usb_reports"] = reports
    out["usb_calibration"] = {
        "model": "gamecube",
        "flash": {f"0x{a:X}": b.hex() for a, b in fake_flash.items()},
        "expected": cal_json(gc_factory),
        "defaults": {m: cal_json(usb.Calibration.defaults(m)) for m in ("gamecube", "pro")},
    }
    out["usb_commands"] = {
        "flash_read": {f"0x{a:X}": usb.flash_read_command(a).hex() for a in (0x13000, 0x13080, 0x130C0, 0x13140, 0x1FC040, 0x1FC060)},
        "led": {str(p): usb.led_command(p).hex() for p in range(0, 9)},
    }

    # --- BLE ---------------------------------------------------------------------------
    out["ble_commands"] = {
        "memory_read": [{"address": f"0x{a:X}", "length": n, "hex": ble.build_memory_read(a, n).hex()}
                        for a, n in ((0x13000, 0x40), (0x13080, 0x40), (0x130C0, 0x40), (0x1FC040, 0x40), (0x13140, 2))],
        "player_leds": {str(p): ble.build_player_leds(p).hex() for p in range(1, 9)},
        "feature_set_mask": ble.build_feature_command(ble.SUB_FEATURE_SET_MASK, ble.DEFAULT_FEATURES).hex(),
        "feature_enable": ble.build_feature_command(ble.SUB_FEATURE_ENABLE, ble.DEFAULT_FEATURES).hex(),
        "rate_descriptor": "8500",
    }
    adverts = []
    for payload in (
        bytes.fromhex("01 00 03 7e 05 73 20 00 00 00 00 00 00 00 00 00 00 00 00".replace(" ", "")),
        bytes.fromhex("01 00 03 7e 05 69 20 00 00 81 88 16 c2 55 e2 98 00 00 00".replace(" ", "")),
        bytes.fromhex("01 00 03 7e 05 66 20 00 00 00 11 22 33 44 55 66 00 00 00".replace(" ", "")),
        bytes.fromhex("01 00 03 4c 05 73 20 00 00 00 00 00 00 00 00 00".replace(" ", "")),
        bytes.fromhex("0100"),
    ):
        adverts.append({"payload": payload.hex(), "expected": ble.parse_manufacturer_data(payload)})
    out["ble_manufacturer_data"] = adverts
    responses = []
    for data in (
        bytes.fromhex("02 01 01 04 00 48 00 00 40 00 00 00 00 30 01 00".replace(" ", "")) + bytes(range(0x40)),
        bytes(14) + bytes.fromhex("09 01 01 07 00 00 00 00".replace(" ", "")),
        bytes.fromhex("00 01 01 04 00 00 00 00".replace(" ", "")),
    ):
        r = ble.parse_command_response(data)
        entry = {"data": data.hex(), "expected": None if r is None else
                 {"cmd": r.cmd, "sub": r.sub, "transport": r.transport, "ack": r.ack, "payload": r.payload.hex()}}
        if r is not None and r.cmd == ble.CMD_FLASH:
            addr, blk = ble.parse_memory_read(r)
            entry["memory"] = {"address": f"0x{addr:X}", "data": blk.hex()}
        responses.append(entry)
    out["ble_command_responses"] = responses
    # BLE report 0x05 = USB report without the id byte; the Java app parses both with the USB
    # code, so these only need to agree within rounding (the Python BLE path uses floats).
    ble_reports = []
    for model in ("gamecube", "pro"):
        for buttons, lx, ly, rx, ry, lt, rt in (({}, 2048, 2048, 2048, 2048, 30, 30),
                                               ({5: 0x04, 7: 0x02}, 3500, 700, 900, 3300, 200, 30)):
            data = usb_report(model, buttons, lx, ly, rx, ry, lt, rt)[1:]
            rep = ble.parse_input_report(model, data, ble.Calibration.default(model))
            ble_reports.append({"model": model, "data": data.hex(), "buttons": rep.buttons,
                                "axes": rep.axes, "raw_buttons": rep.raw_buttons})
    out["ble_reports"] = ble_reports
    out["ble_uuids"] = {
        "service": ble.SERVICE_UUID, "input_common": ble.INPUT_COMMON_UUID,
        "command": ble.COMMAND_UUID, "command_response": ble.COMMAND_RESPONSE_UUID,
        "rate_descriptor": ble.REPORT_RATE_DESCRIPTOR_UUID,
        "models": {k: {"product_id": m.product_id, "report_id": m.report_id, "input": m.input_uuid,
                       "ext_response": m.ext_response_uuid} for k, m in ble.MODELS.items()},
    }
    dst = Path(__file__).with_name("java_vectors.json")
    dst.write_text(json.dumps(out, indent=1) + "\n", encoding="utf-8")
    print(f"wrote {dst} ({dst.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
